const isimler = [
  "Ahmet Yılmaz",
  "Elif Demir",
  "Mehmet Kaya",
  "Zeynep Çelik",
  "Mustafa Şahin",
  "Ayşe Aydın",
  "Ali Yıldız",
  "Fatma Öztürk",
  "Emre Arslan",
  "Merve Doğan",
  "Burak Koç",
  "Selin Yıldırım",
  "Can Özdemir",
  "Esra Aktaş",
  "Kerem Güneş",
  "Derya Aksoy",
  "Oğuz Şimşek",
  "Cansu Korkmaz",
  "Deniz Aydoğan",
  "Melis Erdoğan",
  "Barış Çetin",
  "Seda Polat",
  "Yusuf Kılıç",
  "Nazlı Kara",
  "Hakan Ateş",
  "Ece Avcı",
  "Tuna Yalçın",
  "Pınar Güler",
  "Alp Yavuz",
  "İrem Balcı",
];

const bolgeler = [
  {
    bolge: "Marmara",
    iller: [
      "İstanbul",
      "Bursa",
      "Edirne",
      "Kırklareli",
      "Tekirdağ",
      "Kocaeli",
      "Sakarya",
      "Yalova",
      "Balıkesir",
      "Çanakkale",
      "Bilecik",
    ],
  },
  {
    bolge: "Ege",
    iller: [
      "İzmir",
      "Manisa",
      "Aydın",
      "Denizli",
      "Muğla",
      "Uşak",
      "Kütahya",
      "Afyonkarahisar",
    ],
  },
  {
    bolge: "Akdeniz",
    iller: [
      "Antalya",
      "Isparta",
      "Burdur",
      "Mersin",
      "Adana",
      "Hatay",
      "Kahramanmaraş",
      "Osmaniye",
    ],
  },
  {
    bolge: "İç Anadolu",
    iller: [
      "Ankara",
      "Konya",
      "Eskişehir",
      "Kayseri",
      "Sivas",
      "Çankırı",
      "Kırıkkale",
      "Kırşehir",
      "Nevşehir",
      "Niğde",
      "Aksaray",
      "Yozgat",
      "Karaman",
    ],
  },
  {
    bolge: "Karadeniz",
    iller: [
      "Zonguldak",
      "Bartın",
      "Karabük",
      "Bolu",
      "Düzce",
      "Kastamonu",
      "Sinop",
      "Samsun",
      "Ordu",
      "Giresun",
      "Trabzon",
      "Rize",
      "Artvin",
      "Çorum",
      "Amasya",
      "Tokat",
      "Gümüşhane",
      "Bayburt",
    ],
  },
  {
    bolge: "Doğu Anadolu",
    iller: [
      "Erzurum",
      "Erzincan",
      "Ağrı",
      "Kars",
      "Iğdır",
      "Ardahan",
      "Malatya",
      "Elazığ",
      "Bingöl",
      "Tunceli",
      "Van",
      "Muş",
      "Bitlis",
      "Hakkari",
    ],
  },
  {
    bolge: "Güneydoğu Anadolu",
    iller: [
      "Gaziantep",
      "Kilis",
      "Şanlıurfa",
      "Adıyaman",
      "Diyarbakır",
      "Batman",
      "Şırnak",
      "Siirt",
      "Mardin",
    ],
  },
];

export const regions = bolgeler.map((bolge, bi) => ({
  bolge: bolge.bolge,
  iller: bolge.iller.map((il, ii) => ({
    il,
    temsilci: isimler[(bi * 13 + ii * 7) % isimler.length],
  })),
}));

export const toplamIl = 81;

export const tumIller = regions.flatMap((bolge) => bolge.iller.map((il) => il.il));
